# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dada8087c33d7fcfb1b1fbc5abfab6389fad631d967d2d83d3dc7a0c75bc9d4751bbfbd2483f59aa5e09148cc5943b46dde9dabcb369daf07c6cd01ffb106a61

test:
  secret_key_base: f5f7168934cb492efb0551f94774140d91d0eaedc660ef14881d4786fe3237d80c9674a1b767fc00c7d6c3ab70f1caabc1b6cd38ec6e35591a9c9534be9c0102

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
